name: Wake Streamlit App

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: curl https://hpz-cod-automation.streamlit.app
